import "../css/app.css";
import "../css/swiper.css";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="preload"
          href="/fonts/GothamPro.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/GothamPro-Bold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://cdn.cloudinary.com"
          crossOrigin="anonymous"
        />
        <link
          rel="dns-prefetch"
          href="https://cdn.cloudinary.com"
          crossOrigin="anonymous"
        />
        <link rel="icon" href="/favicon.png" />
      </head>
      <body>
        <div className="main-wrapper">
          <Header />
          <main className="main">
            <div className="container">{children}</div>
          </main>
          <Footer />
        </div>
        <div className="icon-load">
          <div className="ball a"></div>
          <div className="ball b"></div>
          <div className="ball c"></div>
        </div>
      </body>
    </html>
  );
}
